### ISSUE TITLE
install vatz

### ISSUE THREAD

**Issue by heejin-github** [heejin-github/vatz-inventory#1]
```
heejin@bastion-heejin:~/git/vatz-inventory/inventory$ cat inventory.yaml
provenance:
  hosts:
    provenance-testnet-validator-dc-sel2:
    provenance-mainnet-validator-do-sfo2:
    provenance-mainnet-standby-do-nyc3:

chainlink:
  hosts:
    chainlink-agoric-devnet-node1-do-fra1:

assetmantle:
  hosts:
    assetmantle-mainnet-validator-do-sfo2:
    assetmantle-mainnet-standby-dc-sel2:

neutron:
  hosts:
    neutron-mainnet-standby-dc-sel2:
    neutron-mainnet-validator-do-fra1:

berachain:
  hosts:
    berachain-testnet-v2-validator-hetzner-fsn1:
    berachain-testnet-v2-standby-dc-sel2:

```
